name: unit_tests

on: [push, pull_request]

jobs: 
  unit_tests:
    runs-on: ubuntu-latest


    strategy:
      matrix:
        python:
          - '3.10'
        spark:
          - 3.5.1
    
    steps: 
    - uses: actions/checkout@v3
    
    - uses: actions/setup-python@v4
      with: 
        python-version: ${{ matrix.python }}
    
    - uses: actions/setup-java@v3
      with: 
        java-version: '17'
        distribution: 'temurin'
    
    - uses: vemonet/setup-spark@v1
      with: 
        spark-version: ${{ matrix.spark }}
        hadoop-version: '3'
    
    - run: |
        export PYTHONPATH=~/repos/movies_data_cleaning/pipeline_code/
        pwd